services:

    motherbrain.sylius_payum_stripe_subscription.form.type.gateway_configuration.stripe_js_subscription:
        class: Motherbrain\SyliusPayumStripeSubscriptionPlugin\Form\Type\StripeJsSubscriptionGatewayConfigurationType
        tags:
          - { name: sylius.gateway_configuration_type, type: stripe_js_subscription, label: stripe_js_subscription }
